version: '3.8'

services:
  umbraco:
    image: istanbul-eventz-cms
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./appdata:/app/Data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
