version: '3.8'

services:
  umbraco:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: umbraco_app
    ports:
      - "5000:80"
    depends_on:
      - db
    restart: always

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Merve3823ismail.
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    command: >
      bash -c '
      /opt/mssql/bin/sqlservr &
      sleep 30 &&
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Merve3823ismail. -d master -i /docker-entrypoint-initdb.d/init-db.sql
      '
    restart: always

volumes:
  sqlserver_data: